config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'all_users' => 'epicenter#all_users'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'

  resources :tweeters
  devise_for :users

  # root 'tweeters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags
  has_many :tweeters, through: :tweet_tags
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweeter
  belongs_to :tag
end

app/models/tweeter.rb
class Tweeter < ApplicationRecord
  belongs_to :user

  has_many :tweet_tags
  has_many :tags, through: :tweet_tags

  before_validation :link_check, on: :create

  validates :message, presence: true
  validates :message, length: {maximum: 140}, on: :create

  after_validation :apply_link, on: :create

private

def link_check
  check = false
  if self.message.include? "http://"
    check = true
  elsif self.message.include? "https://"
    check = true
  else
    check = false
  end

  if check == true
    arr = self.message.split
    index = arr.map{ |x| x.include?("http://") || x.include?("https://")}.index(true)
    self.link = arr[index]
    if arr[index].length > 23
      arr[index] = "{arr[index][0...20]}..."
    end

    # self.message = arr.join(" ")
  end
end

def apply_link
  arr = self.message.split
  index = arr.map{ |x| x.include?("http://") || x.include?("https://")}.index(true)

  if index
    url = arr[index]
    arr[index] = "<a href='#{self.link}' taget='_blank'>#{url}</a>"
  end

  self.message = arr.join(" ")

end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :username, presence: true
  validates :username, uniqueness: true
  # could also do validates :username, presence: true, uniqueness: true
  
  serialize :following, Array


  has_many :tweeters

  mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception
  # for APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  before_action :authenticate_user!

  def feed
    @following_tweeters = []

    Tweeter.all.each do |tweet|
      if
        current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
        @following_tweeters.push(tweet)
        # puts current_user.id.to_s + " ones"
        # puts tweet.user_id.to_s + " two"
        # puts tweet
      end
    end
  end

  def all_users
    @users = User.all
  end

  def show_user
    @user = User.find(params[:id])
  end


  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def now_following
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end

end

app/controllers/tweeters_controller.rb
class TweetersController < ApplicationController
  before_action :set_tweeter, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  include TweetersHelper

  # GET /tweeters
  # GET /tweeters.json
  def index
    @tweeters = Tweeter.all
  end

  # GET /tweeters/1
  # GET /tweeters/1.json
  def show
  end

  # this method gets the form ready, doesn't save anything
  # GET /tweeters/new
  def new
    @tweeter = Tweeter.new
  end

  # GET /tweeters/1/edit
  def edit
  end

  # method saves the tweet (uses the 'new' form and saves the changes; almost like update)
  # POST /tweeters
  # POST /tweeters.json
  def create

    @tweeter = Tweeter.create(tweeter_params)

    @tweeter = get_tagged(@tweeter)

    respond_to do |format|
      if @tweeter.save
        format.html { redirect_to @tweeter, notice: 'Tweeter was successfully created.' }
        format.json { render :show, status: :created, location: @tweeter }
      else
        format.html { render :new }
        format.json { render json: @tweeter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeters/1
  # PATCH/PUT /tweeters/1.json
  def update
    respond_to do |format|
      if @tweeter.update(tweeter_params)
        format.html { redirect_to @tweeter, notice: 'Tweeter was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeter }
      else
        format.html { render :edit }
        format.json { render json: @tweeter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeters/1
  # DELETE /tweeters/1.json
  def destroy
    @tweeter.destroy
    respond_to do |format|
      format.html { redirect_to tweeters_url, notice: 'Tweeter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeter
      @tweeter = Tweeter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweeter_params
      params.require(:tweeter).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweeters_helper.rb
module TweetersHelper
  def get_tagged(tweeter)

      message_arr = Array.new
      message_arr = tweeter.message.split
      message_arr.each_with_index do |word, index|

        if word[0] == "#"
          if Tag.pluck(:phrase).include?(word.downcase)
            tag = Tag.find_by(phrase: word.downcase)
          else
            tag = Tag.create(phrase: word.downcase)
          end
            # this line is setting the tweed id in the Tag table from the Tweeters table
            tweet_tag = TweetTag.create(tweet_id: tweeter.id, tag_id: tag.id)
            message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
        end
      end

      tweeter.update(message: message_arr.join(" "))
      return tweeter
  end
end

app/views/epicenter/_user_list.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-3">
      <div class="well user-list-wells">
        <div class="row">
          <div class="col-md-6">
             <% if user.avatar.blank? == false %>
              <%= image_tag user.avatar.url, size:50, class: "user-pic-nav"  %>
              <% end %>
          </div>
          <div class="col-md-6">
            <p>
              <% if current_user.following.include?(user.id) %>
                <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
              <% else %>
                <% if current_user.id != user.id %>
                  <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
        <div class="row">
          <%= link_to show_user_path(id: user.id) do %>
            <h3><%= user.name %></h3>
            <p>@<%= user.username %></p>
          <% end %>
          <p>
            <%= user.bio %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/epicenter/all_users.erb
<h2>All Users</h2>
<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12"></div>

        <h1>@<%= current_user.username %>'s Twitter Feed</h1>
        <p>Here is what your friends are saying:</p>
      </div>

    <div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
      <p><%= current_user.username %>
      </div>
      </div>
    </div>

<div class="col-md-8">
  <div class="panel panel-default">
  <% @following_tweeters.reverse.each do |tweet| %>

  <div class="panel-heading">
  <p>
    <% if tweet.user.avatar.blank? == false %>
    <%= image_tag tweet.user.avatar.url, size:50, class: "user-pic-nav" %>
    <%=tweet.user.name %>
    <% end %> @
    <%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %>  • <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
    <%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>
  </p>
  </div>
  <div class="panel-body">
  <p><%= tweet.message.html_safe %></p>
</div>
<% end %>
</div>
  </div>
  </div>

app/views/epicenter/feed_good.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-12"></div>
      <h1>@<%= current_user.username %>'s Twitter Feed</h1>
    </div>

      <p>Here is what your friends are saying:</p>

  <div class="col-md-2"></div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <p><%= current_user.username %>
            <% @following_tweeters.reverse.each do |tweet| %>
            <!-- <div class="row"> -->
              <div class="col-md-8">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <p>
                      <% if tweet.user.avatar.blank? == false %>
                      <%= image_tag tweet.user.avatar.url, size:50, class: "user-pic-nav" %>
                      <%=tweet.user.name %>
                      <% end %> @
                      <%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %>  • <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
                      <%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>
                    </p>
                  </div>
                <div class="panel-body"><p><%= tweet.message.html_safe %></p></div>
            </div>
          </div>
          <div class="col-md-2"></div>
        <!-- </div> -->
        <% end %>
      </div>
    </div>
  </div>

app/views/epicenter/followers.html.erb
<h2><%= @user.name %>'s Followers</h2>
<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h2><%= @user.name %></h2>
<%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12"></div>

<h1>@<%= @user.username %>'s Profile & Tweets</h1>
  </div>

  <div class="row">
    <div class="col-sm-6"></div>
      <div class="panel panel-default">

        <div class="panel-heading">
<div><%= @user.name %></div>
<div><%= @user.location %></div>
<div><%= @user.bio %></div>
    </tr>
</div>

  <div class="panel-body">

  <% if current_user.following.include?(@user.id) %>
    <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-danger", id: "unfollow_btn" %>
  <% else %>
    <% if current_user.id != @user.id %>
      <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
    <% end %>
  <% end %>
  </div>


<% @user.tweeters.each do |tweet| %>
  <div class="row">
    <div class="col-sm-6"></div>
      <div class="panel panel-default">
  <div>
    <p>@<%= @user.username %></p>
    <p>@<%= tweet.message %></p>
  </div>
    </div>

  </div>
<% end %>

  </div>
  </div>

app/views/epicenter/tag_tweets.html.erb
<div>
  <h1><%= @tag.phrase %></h1>
</div>

<div class="row">

  <div>
    <% @tag.tweeters.order(created_at: :desc).each do |tweet| %>
    <p>
      <%= tweet.user.name %> <%= "@#{tweet.user.username}" %>
        <%= time_ago_in_words(tweet.created_at) %>
    </p>
    <p>
      <%= tweet.message.html_safe %>
    </p>
  <% end %>
  </div>
</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<!-- app/views/layouts/application.html.erb -->
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Tweet", new_tweeter_path %></li>
          <li><%= link_to "All Users", all_users_path %></li>
      
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.avatar.blank? == false %>
                  <%= image_tag current_user.avatar.url, size:25, class: "user-pic-nav" %>
                <% end %>
                @<%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
	<div class="container">
    <%= yield %>
	</div>
</body>

</html>

app/views/tweeters/_form.html.erb
<%= form_with(model: tweeter, local: true) do |form| %>
  <% if tweeter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweeter.errors.count, "error") %> prohibited this tweeter from being saved:</h2>

      <ul>
      <% tweeter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
<div class="row">
  <div class="col-md-8">

  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_area :message, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>

  </div>
  </div>
  </div>
  <div class="col-md-4"></div>



  <div class="actions">
    <%= form.submit "Tweeter It!", class: "btn btn-primary" %>
  </div>
    </div>
<% end %>

app/views/tweeters/edit.html.erb
<h1>Editing Tweeter</h1>

<%= render 'form', tweeter: @tweeter %>

<%= link_to 'Show', @tweeter %> |
<%= link_to 'Back', tweeters_path %>

app/views/tweeters/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="row">
    <div class="col-md-12"></div>
<h1>Tweeters</h1>
  </div>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweeters.each do |tweeter| %>
      <tr>
        <td><%= tweeter.message.html_safe %></td>
        <td><%= link_to tweeter.user.username, show_user_path(id: tweeter.user.id) %></td>
        <td><%= link_to 'Show', tweeter %></td>
        <td><%= link_to 'Edit', edit_tweeter_path(tweeter) %></td>
        <td><%= link_to 'Destroy', tweeter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweeter', new_tweeter_path %>

app/views/tweeters/new.html.erb
<div class="container">

    <div class="row">
      <div class="col-md-12"></div>
      <h1>New Tweeter</h1>
    </div>
</div>

<%= render 'form', tweeter: @tweeter %>

<%= link_to 'Back', tweeters_path %>

app/views/tweeters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweeter.message.html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweeter.user.username, show_user_path(id: @tweeter.user.id) %>
</p>

<%= link_to 'Edit', edit_tweeter_path(@tweeter) %> |
<%= link_to 'Back', tweeters_path %>